spring.application.name=senamhi

server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BD_SENAMHI;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=cibertecsqlserver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect